site_name: Siddhi IO TCP
site_description: Siddhi IO TCP Extension
repo_name: Siddhi IO TCP
repo_url: https://github.com/siddhi-io/siddhi-io-tcp/
edit_uri: https://github.com/siddhi-io/siddhi-io-tcp/blob/master/
copyright: Siddhi - Documentation
theme:
  name: material
  logo: images/siddhi-logo.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
extra_css:
- assets/stylesheets/extra.css
extra_javascript:
- assets/javascripts/extra.js
extra:
  social:
  - type: github
    link: https://github.com/siddhi-io/siddhi
  - type: medium
    link: https://medium.com/siddhi-io
  - type: twitter
    link: https://twitter.com/siddhi_io
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
google_analytics:
- UA-103065-28
- auto
markdown_extensions:
- markdown.extensions.admonition
pages:
- Information: index.md
- API Docs:
  - latest: api/latest.md
  - 3.0.3: api/3.0.3.md
  - 3.0.2: api/3.0.2.md
  - 3.0.1: api/3.0.1.md
  - 3.0.0: api/3.0.0.md
  - 2.1.2: api/2.1.2.md
  - 2.1.1: api/2.1.1.md
  - 2.1.0: api/2.1.0.md
  - 2.0.20: api/2.0.20.md
  - 2.0.19: api/2.0.19.md
  - 2.0.18: api/2.0.18.md
  - 2.0.17: api/2.0.17.md
  - 2.0.16: api/2.0.16.md
  - 2.0.15: api/2.0.15.md
  - 2.0.14: api/2.0.14.md
  - 2.0.13: api/2.0.13.md
  - 2.0.12: api/2.0.12.md
  - 2.0.11: api/2.0.11.md
  - 2.0.10: api/2.0.10.md
  - 2.0.9: api/2.0.9.md
  - 2.0.8: api/2.0.8.md
  - 2.0.7: api/2.0.7.md
- License: license.md
