site_name: Siddhi-IO-TCP
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi IO TCP: index.md
- API Docs:
  - 2.0.3-SNAPSHOT: api/2.0.3-SNAPSHOT.md
  - 2.0.6-SNAPSHOT: api/2.0.6-SNAPSHOT.md
- License: license.md
theme: material
